### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by Serzariax** [thingsboard/flutter_thingsboard_pe_app#9] opened 2022-03-22 12:48 UTC
Hello

I followed "https://thingsboard.io/docs/pe/mobile/getting-started/" to test the app on my android (using ThingsBoard Cloud).
It gets stuck at loading but if I close the app and open it again it goes to the login page. Also at login page soon as I try to login it loads continuously but if I l close and open the app it logins in correctly. Also when I'm not using ThingsBoard Cloud I have the same issue.

**Comment by ybeshkarov** [comment] 2024-05-29 12:35
Hello @Serzariax,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-29 12:35 UTC
