### ISSUE TITLE
IOS infinite loading after login 

### ISSUE THREAD

**Issue by Mark-MV-Wizard** [thingsboard/flutter_thingsboard_pe_app#113] opened 2024-07-16 07:09 UTC
I have noticed that when trying to run the iOS version of the app, the app has an infinite loading screen and does not load any dashboard as shown in the picture. I originally tested it with the code I was working with from version 1.1.0 but now using the latest release, without any changes aside from the endpoint string, I still get the same error, please may you assist 
![image](https://github.com/user-attachments/assets/c6741a4e-69cf-44cd-b3c8-5c3155b999b5)

I am using the iOS simulator as well as the things board PE of the app.  My ide is using FVM with flutter 3.19.6. Ive tested on android, and it works but IOS has the spinning issue

**Comment by ybeshkarov** [comment] 2024-07-16 08:11
Hi @Mark-MV-Wizard,

Do you see any error messages in your console? 
Which IOS version is for your simulator?

**Comment by Mark-MV-Wizard** [comment] 2024-07-16 08:45
Hi @ybeshkarov thank you for your quick reply 
I am using IOS 17.5 with iphone 15 on the simulator , also tried it with the iphone SE on teh simulator but with the same result

I am looking at the console at the debug logs and I don't see any errors in particular, it seems to have retrieved the dashboard token and ends with the path/home as the last debug message

**Comment by WillieSpence** [comment] 2024-07-16 08:51
@Mark-MV-Wizard , I vaguely remember having a similar issue and if I remember correctly it was something with the default dashboard that was set for the user. Once I removed the default dashboard for the user, it managed to load the dashboard screen from where the user can then choose his dashboard. 

I haven't tested this with the latest version, but I remember with the initial release of the app the issue was there, so not sure if it has since been fixed.

Maybe worth a shot to see if it could be what you are facing.

**Comment by Mark-MV-Wizard** [comment] 2024-07-16 08:55
@WillieSpense thank you for your response. It has to set the default dashboard for the user as per requirements the user needs to have access to the contents of that specific dashboard and not be able to access the other dashboards on the system, as thus the dashboard selector functionality is disabled for the user account

**Comment by Sekiro-kost** [comment] 2024-07-17 10:56
> Hi @ybeshkarov thank you for your quick reply I am using IOS 17.5 with iphone 15 on the simulator , also tried it with the iphone SE on teh simulator but with the same result
> 
> I am looking at the console at the debug logs and I don't see any errors in particular, it seems to have retrieved the dashboard token and ends with the path/home as the last debug message
> 
> are there any other details or actions in which I can help to diagnose this issue?

Hello

I had exactly the same issue
On my iPhone, on simulator

**Comment by ybeshkarov** [comment] 2024-07-17 14:09
@Sekiro-kost could you add details on how to reproduce it?

Unfortunately, I'll not be able to help you without technical details or steps to reproduce.

**Comment by Sekiro-kost** [comment] 2024-07-17 14:16
![SCR-20240717-ogrr](https://github.com/user-attachments/assets/ccab1704-b642-4fd2-ab81-0c2e47a574c2)
![SCR-20240717-ogyr](https://github.com/user-attachments/assets/87bc8e14-861b-4cc1-8ff8-d31a2cf29739)
![SCR-20240717-ohcg](https://github.com/user-attachments/assets/56ea228f-7ee5-423b-aab8-547ad000906e)
![SCR-20240717-ohfl](https://github.com/user-attachments/assets/b3592cf8-fbc9-4307-9b23-52a88dbfb5ee)


Here my Xcode console debug. 

And after login, same as @Mark-MV-Wizard 

The home dashboard is loading infinite, not display him

**Comment by Mark-MV-Wizard** [comment] 2024-07-18 09:26
@ybeshkarov 
to show you the steps 
1. I downloaded flutter version manager
2. I switched to flutter version 3.19.6
3. I cloned the repository for the latest release of the app version 1.2.0 of the thingsboard PE
4. I started the IOS simulator  using iOS 17.5 and iPhone 15
5. I changed the API endpoint to my custom server that is serving things board PE. It does successfully work for android
6. I used the command ```fvm flutter run```
7. I see my white labelled logo displaying but when logging in there is an infinite loader showing
here is my debug log with the sensitive information blocked
8. I log in and the infinite loader appears

![image](https://github.com/user-attachments/assets/73190a8f-e211-49c7-be58-9c69366566d4)


% fvm flutter run                                                        
Launching lib/main.dart on iPhone 15 in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.6s
Xcode build done.                                           38.4s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Syncing files to device iPhone 15...                               186ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 15 is available at: http://127.0.0.1:49647/9sAvJUaObsQ=/
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::getItem(thingsBoardApiEndpoint)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext::init() endpoint:###
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
The Flutter DevTools debugger and profiler on iPhone 15 is available at: ###uri=###
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::getItem(jwt_token)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::getItem(refresh_token)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::deleteItem(jwt_token)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::deleteItem(refresh_token)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext.onUserLoaded: isAuthenticated=false
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext:updateRouteState() true
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext:updateRouteState() true
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::getItem(initialAppLink)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::setItem(jwt_token, ###
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::setItem(refresh_token, ###
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext.onUserLoaded: isAuthenticated=true
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 authUser: AuthUser####
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::getItem(thingsBoardApiEndpoint)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext:updateRouteState() true
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::getItem(thingsBoardApiEndpoint)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 TbContext: On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onWebViewCreated
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onUpdateVisitedHistory: ###
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 LocalDatabaseService::getItem(thingsBoardApiEndpoint)
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 shouldOverrideUrlLoading ###
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onLoadStart: ###
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by ybeshkarov** [comment] 2024-07-18 14:45
Can someone email me test credentials with an endpoint where this issue is reproducible? 
I tried on my test environment but I'm unable to catch it at all.

**Comment by leorenan** [comment] 2024-07-19 23:45
> Can someone email me test credentials with an endpoint where this issue is reproducible? I tried on my test environment but I'm unable to catch it at all.


What would be your email, I can forward one for testing, as I have the same problem in the issue https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/89

**Comment by ybeshkarov** [comment] 2024-07-21 13:59
@leorenan dashboard is not loading and home screen is not loading it's a bit different issues.

**Comment by Mark-MV-Wizard** [comment] 2024-07-22 07:46
Hi @ybeshkarov thank you so much for your assistance

I'm not 100 percent sure , but I suspect that after I had my developer account approved, my app started functionally loading the dashboard and working on the simulator  for iPhone 15 version 17.5 using version 1.1.0 as the base thingsboard PE flutter app

However I am unsure now why I am unable to run it on my physical  iPhone 6 running iOS version 12.5.7 , I have specified the minimum build version to 12 and I have seen the issue about Xcode causing errors when running builds from cloud based files and thus I have moved it to my local drive.

I have tried a build with the base settings, I have tried with and without the recommended update setting that Xcode warns.
I have tried to remove the Pod files and re initializing them. The flutter iOS official documentation does not seem to be much help 

I get this error:
Target debug_unpack_ios failed: Exception: Failed to codesign /Users/#####/Library/Developer/Xcode/DerivedData/Runner-aitxbwbduqyisldslahehbuivwzw/Build/Products/Debug-iphoneos/Flutter.framework/Flutter with identity ############


how do I solve this Xcode issue?

**Comment by ybeshkarov** [comment] 2024-07-22 09:39
Honestly, I'm not sure you will be able to build the app for such an old iOS version. But you may try and google the issues you will obtain. 
@Mark-MV-Wizard

**Comment by Mark-MV-Wizard** [comment] 2024-07-22 09:43
ahh i thought so as much , I will try with a newer version . Is there a minimum ios version and phone for the thingsboard PE app to work on ?

**Comment by Sekiro-kost** [comment] 2024-07-22 09:57
For the pb I had, same @Mark-MV-Wizard , I'm on my iPhone 13 iOS 17, and 12.0 minimum on Xcode

**Comment by ybeshkarov** [comment] 2024-07-22 10:54
The minimum deployment target and deployment target is IOS 12, you may see it in Xcode.
@Mark-MV-Wizard

**Comment by Mark-MV-Wizard** [comment] 2024-07-22 11:11
@ybeshkarov
Googling my errors did'nt seem to come into any help with my xcode errors. 
Im also a bit confused because you did say that it will not be able to be deployed for such an old IOS version and I am using ios 12.4 on an iphone 6. If this is too old to build the app will the Thingsboard app Flutter PE  work on an iphone SE 2nd Gen running IOS 17.5 work instead ( i want to confirm this before i buy the device to test)

Thank you again for your help @ybeshkarov

**Comment by ybeshkarov** [comment] 2024-07-22 11:56
I didn't try to build for IOS 12. I say I'm not sure :)
Well, technically I'm not able to check if it's possible. I can't download the simulator with IOS 12 and don't have such a device.

It should work on iPhones with iOS 17.5. 
@Mark-MV-Wizard

**Comment by ybeshkarov** [comment] 2024-07-26 07:09
HI @Mark-MV-Wizard,

It should be okay, I plan to add the same for the next release. The Flutter web view example does the same.

<img width="1658" alt="Screenshot 2024-07-26 at 10 09 19" src="https://github.com/user-attachments/assets/e8bd5a5d-5ff3-4ffe-82c9-d76850e7f477">

**Comment by Mark-MV-Wizard** [comment] 2024-07-26 08:29
thanks @ybeshkarov  :D, I can close this issue now if you like

**Comment by Sekiro-kost** [comment] 2024-07-26 08:32
> thanks @ybeshkarov :D, I can close this issue now if you like

Close this issue ? 
Where is the solution for the infinite loop ? 
Did I miss something

**Comment by ybeshkarov** [comment] 2024-07-27 18:16
Guys, could you please build your app from the `hotfix` source branch and check if it's fixed for your environment?

@Sekiro-kost @Mark-MV-Wizard

**Comment by Sekiro-kost** [comment] 2024-07-27 19:24
> Guys, could you please build your app from the `hotfix` source branch and check if it's fixed for your environment? #116
> 
> @Sekiro-kost @Mark-MV-Wizard

I tried it. And it's the same in debug mode, on my iPhone 13. :(

**Comment by ybeshkarov** [comment] 2024-07-28 07:27
@Sekiro-kost 
The same in debug mode is it loading spinner when you try to sign in?
![image](https://github.com/user-attachments/assets/d1f86fdf-301b-4d04-af95-2e2924eca5da)

**Comment by Sekiro-kost** [comment] 2024-07-28 09:27
@ybeshkarov 

Not exaclty, I don't see login input when the loading is here


![IMG_6035](https://github.com/user-attachments/assets/74233cf1-557e-47a9-912f-596830a4cae4)

**Comment by ybeshkarov** [comment] 2024-08-01 09:39
@Sekiro-kost it's a known issue https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/89
We are working to fix it.

**Comment by ybeshkarov** [comment] 2024-08-01 10:15
Fixes for the issue were provided in the `master` and `release/1.2.0` branches.

**Closed by ybeshkarov** 2024-08-01 10:15 UTC
