### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by diegus22** [thingsboard/flutter_thingsboard_pe_app#5] opened 2022-02-04 22:13 UTC
Hello,

The first time I run the application in the Ios simulator, it gets stuck in the initial screen, in order to continue I have to stop the simulation and restart the application, in this case, I access the login screen and I can enter the credentials, but it gets stuck again, it is in the third run when I can actually enter the dashboard.
![152518118-7bf07d7a-cbf3-40da-96bd-e5e6e36793fd](https://user-images.githubusercontent.com/333989/152610233-3a4aba49-208f-44d3-a8cf-9e445fe88356.png)

**Comment by duerreda** [comment] 2022-03-22 13:02
Hi, we ran into the same issue. Analysis has shown that the white-labeling code is responsible for the error, particularly the section where FavIcon are handled. As a quick-fix, we commented out lines 261 and 262 in wl_service.dart. Compiles and runs seamlessly now.

![image](https://user-images.githubusercontent.com/13023450/159487929-9b203621-011d-4166-9f0a-230e522e8cf5.png)

**Comment by alkortius** [comment] 2022-04-01 09:38
Thanks. 
One hand I've commented those lines and now my emulator doesn't stop, work well. But the other hand I create app.apk and appear that I can't install. I don't know why.

**Comment by alkortius** [comment] 2022-04-07 11:14
Thanks. 
One hand I've commented those lines and now my emulator doesn't stop, work well. But the other hand I create app.apk and appear that I can't install. I don't know why

https://youtu.be/wpjbf4sXzfw
![image](https://user-images.githubusercontent.com/2829969/162184104-03f6b5c7-3033-4594-9d7d-6999182e7dcf.jpg)

**Comment by ybeshkarov** [comment] 2024-05-29 12:32
Hello @diegus22,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-29 12:32 UTC
