### ISSUE TITLE
Unable to access dashboard

### ISSUE THREAD

**Issue by yunamoon** [thingsboard/flutter_thingsboard_pe_app#34] opened 2023-02-08 06:49 UTC
Hello. 
I'm having a hard time using the mobile app. 

I ran the flutter project with an Android emulator. 
After logging in, other things work fine. 
But I can't access the dashboard. 
If you select a dashboard, it becomes an infinite wait state. 

I want to find a solution.

**Comment by MM-06** [comment] 2023-02-15 11:25
Hi, what version of thingsboard platform you using?

**Comment by yunamoon** [comment] 2023-02-20 04:32
@MM-06  HI, thank you for leaving a comment. I'm using things board cloud. Is there a problem if the version is different? The thingsboard_pe_client version is 1.0.5.

**Comment by ybeshkarov** [comment] 2024-05-28 12:09
Hello @yunamoon,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-28 12:09 UTC
