### ISSUE TITLE
App Stuck on Loading

### ISSUE THREAD

**Issue by chatchai-bix** [thingsboard/flutter_thingsboard_pe_app#3] opened 2021-12-10 21:02 UTC
Hello

I followed "https://thingsboard.io/docs/pe/mobile/getting-started/" to test the app on my android (using ThingsBoard Cloud). Everything worked fine on an emulator but when I run the app on my phone (Samsung Galaxy S10), It stuck on loading screen and can't do anything.

**Comment by ybeshkarov** [comment] 2024-05-29 12:28
Hello @chatchai-bix,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-29 12:28 UTC
