### ISSUE TITLE
Unable to login and view dashboard

### ISSUE THREAD

**Issue by MM-06** [thingsboard/flutter_thingsboard_pe_app#28] opened 2022-12-20 12:25 UTC
Hey guys,

I've followed all the steps from the setup tutorial (https://thingsboard.io/docs/pe/mobile/getting-started/) accurately. If I set the endpoint to the ThingsBoard cloud (https://thingsboard.cloud/) then the app works perfectly, but if I set the endpoint to my ThingsBoard PE server instance, then I can't login to the app. On the server, under audit logs, it does indicate a successful login however nothing changes on the app. Has anyone experienced this problem or could they advise on a solution? Thanks

**Comment by badril1978** [comment] 2022-12-28 06:54
Same problem here. I can't even login to thingsboard cloud let alone my PE server. Did you use tenant@thingsboard.org as username and tenant as password?

**Comment by MM-06** [comment] 2022-12-28 07:27
No, for the cloud I created an account first and then used that credentials to login on the app.

**Comment by MM-06** [comment] 2022-12-28 07:30
Ok after some time, I think that the ThingsBoard client library in the latest app code is for ThingsBoard PE version 3.4.2. So I've used an older commit from April (https://github.com/thingsboard/flutter_thingsboard_pe_app/tree/6bbe02b932f48e47d90698b2990af8706dbf3443) and after a few hours of fixing errors it works. I recommend perhaps using this commit instead.

**Comment by ashvayka** [comment] 2023-01-09 13:23
@vvlladd28 please take a look

**Comment by ybeshkarov** [comment] 2024-05-28 12:15
Hello @MM-06,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-28 12:15 UTC
