### ISSUE TITLE
Cannot login...

### ISSUE THREAD

**Issue by AngeLinuX99** [thingsboard/flutter_thingsboard_pe_app#23] opened 2022-11-04 09:25 UTC
Hi, 

When Im login from android app to my platform, it never logs in and bring me back to login screen again. No messages, no errors, nothing... can you help me to fix this issue ?

-------
An Observatory debugger and profiler on M2101K9AG is available at: http://127.0.0.1:51639/VGPNiLyLgtA=/
The Flutter DevTools debugger and profiler on M2101K9AG is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51639/VGPNiLyLgtA=/
I/flutter ( 6014):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6014):   ERROR │ ThingsboardError: message: [Unsupported ThingsBoard platform version: 3.3.4.1PE], errorCode: 2, status: null
I/flutter ( 6014):   ERROR │ #0      toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter ( 6014):   ERROR │ #1      ThingsboardClient.init (package:thingsboard_pe_client/src/thingsboard_client_base.dart:232:13)
I/flutter ( 6014):   ERROR │ <asynchronous suspension>
I/flutter ( 6014):   ERROR │ #2      TbContext.init (package:thingsboard_app/core/context/tb_context.dart:187:7)
I/flutter ( 6014):   ERROR │ <asynchronous suspension>
I/flutter ( 6014):   ERROR │ #3      HasTbContext.initTbContext (package:thingsboard_app/core/context/tb_context.dart:640:5)
I/flutter ( 6014):   ERROR │ <asynchronous suspension>
I/flutter ( 6014):   ERROR │
I/flutter ( 6014):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6014):   ERROR │ #0   ThingsboardClient.init (package:thingsboard_pe_client/src/thingsboard_client_base.dart:232:7)
I/flutter ( 6014):   ERROR │ #1   <asynchronous suspension>
I/flutter ( 6014):   ERROR │ #2   TbContext.init (package:thingsboard_app/core/context/tb_context.dart:187:7)
I/flutter ( 6014):   ERROR │ #3   <asynchronous suspension>
I/flutter ( 6014):   ERROR │ #4   HasTbContext.initTbContext (package:thingsboard_app/core/context/tb_context.dart:640:5)
I/flutter ( 6014):   ERROR │ #5   <asynchronous suspension>
I/flutter ( 6014):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6014):   ERROR │ ⛔ Failed to init tbContext: ThingsboardError: message: [Unsupported ThingsBoard platform version: 3.3.4.1PE], errorCode: 2, status: null
I/flutter ( 6014):   ERROR │ ⛔ #0      toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter ( 6014):   ERROR │ ⛔ #1      ThingsboardClient.init (package:thingsboard_pe_client/src/thingsboard_client_base.dart:232:13)
I/flutter ( 6014):   ERROR │ ⛔ <asynchronous suspension>
I/flutter ( 6014):   ERROR │ ⛔ #2      TbContext.init (package:thingsboard_app/core/context/tb_context.dart:187:7)
I/flutter ( 6014):   ERROR │ ⛔ <asynchronous suspension>
I/flutter ( 6014):   ERROR │ ⛔ #3      HasTbContext.initTbContext (package:thingsboard_app/core/context/tb_context.dart:640:5)
I/flutter ( 6014):   ERROR │ ⛔ <asynchronous suspension>
I/flutter ( 6014):   ERROR │ ⛔
I/flutter ( 6014):   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/DecorView[]( 6014): onWindowFocusChanged hasWindowFocus false

**Comment by bramkennis** [comment] 2022-11-24 14:36
Hi @AngeLinuX99 , I have just the same problem. I see in the logs Unsupported ThingsBoard platform version: 3.3.4.1PE but it should be possible from 3.3.0.
Did you get it working?

**Comment by MM-06** [comment] 2022-12-12 14:37
@AngeLinuX99 @bramkennis I am having the same problem, please advise if you guys have a solution. Thanks.

**Comment by Aviijit** [comment] 2023-02-02 03:52
Any update on this ?
I'm also facing same issue after changing thingsBoardApiEndpoint from "https://demo.thingsboard.io" to my machine IP. Please help here.

**Comment by Maxwh21** [comment] 2023-02-06 10:14
same issue here

**Comment by jh83** [comment] 2023-02-22 12:22
Same issue here. Running PE 3.4.1. 

Tried to clone the code today and got this issue. Did it about 1 month ago, and the APK i built that time is still working, but not the on that i build on the newly cloned git repository.

**Comment by ybeshkarov** [comment] 2024-05-29 13:39
Hello @AngeLinuX99,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-29 13:39 UTC
