### ISSUE TITLE
login and password, it runs and then we stay on the stack

### ISSUE THREAD

**Issue by rocket13011** [thingsboard/flutter_thingsboard_pe_app#40] opened 2023-03-08 18:17 UTC
Hello,

I compiled the application for iOS but I'm still stuck on the login page.

If I put a login and password, it runs and then we stay on the stack

we can see in this login page the logo of our company, so it means that it is well linked to our server.

and on our server we see in the audit that there is a successful connection

I forgot something ?

With kind regards.

**Comment by ybeshkarov** [comment] 2024-05-28 12:01
Hello @rocket13011,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-28 12:01 UTC
