### ISSUE TITLE
self-registration flow failed

### ISSUE THREAD

**Issue by moshe-kabala** [thingsboard/flutter_thingsboard_pe_app#4] opened 2021-12-26 18:33 UTC
After setting up google auth provider I got the error below
It fixed by removing the Expanded widget from core/auth/login_page.dart:324

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building _OutlinedButtonWithIconChild(dependencies: [MediaQuery]):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5055 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
```

**Comment by AminfiBerlin** [comment] 2022-05-15 11:57
Hi,
I'm getting the same error. Is there any update on this issue?

**Comment by ybeshkarov** [comment] 2024-05-29 12:30
Hello @moshe-kabala,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!

**Closed by ybeshkarov** 2024-05-29 12:30 UTC
